// Mock data for Post Optimizer Agent
// Used when USE_MOCK_DATA=true

function getMockPostPackage(niche, hashtags) {
  const nicheTag = niche.toLowerCase().replace(/\s+/g, '');

  return {
    captions: [
      {
        variant: 'A',
        text: `What if Atlantis was rebuilt with AI? 🌊\n\nEvery single frame generated by artificial intelligence.\nNo cameras. No CGI studio. No team.\nJust me, a prompt, and a dollar.\n\nCould you tell it was AI? Drop a 🤔 below\n\n${niche} has never looked like this before.`,
        hook: `What if Atlantis was rebuilt with AI? 🌊`,
        cta: `Could you tell it was AI? Drop a 🤔 below`
      },
      {
        variant: 'B',
        text: `POV: You discover an AI-generated underwater city 🏙️🌊\n\nThis didn't exist 3 minutes ago.\nAI dreamed it up, frame by frame.\n\nThe future of content creation is here —\nand it costs less than your morning coffee.\n\nWould you live in this city? Comment below 👇\n\n#${nicheTag} #aigenerated`,
        hook: `POV: You discover an AI-generated underwater city 🏙️🌊`,
        cta: `Would you live in this city? Comment below 👇`
      }
    ],
    hashtags: {
      niche: [
        `#${nicheTag}daily`,
        '#texttoimage',
        '#generativeart',
        '#aiimages',
        '#neuralart',
        '#deeplearningart',
        '#aiartist',
        '#machinelearningart',
        '#algorithmicart',
        '#computationalart'
      ],
      medium: [
        '#aiart',
        '#aigenerated',
        '#aiartcommunity',
        '#digitalartist',
        '#conceptart',
        '#scifiart',
        '#fantasyart',
        '#futurism',
        '#digitalpainting',
        '#artoftheday'
      ],
      broad: [
        '#art',
        '#digitalart',
        '#creative',
        '#artwork',
        '#artist',
        '#illustration',
        '#design',
        '#creativity',
        '#beautiful',
        '#inspiration'
      ],
      formatted: `#${nicheTag}daily #texttoimage #generativeart #aiimages #neuralart #deeplearningart #aiartist #machinelearningart #algorithmicart #computationalart #aiart #aigenerated #aiartcommunity #digitalartist #conceptart #scifiart #fantasyart #futurism #digitalpainting #artoftheday #art #digitalart #creative #artwork #artist #illustration #design #creativity #beautiful #inspiration`
    },
    postingStrategy: {
      bestTimes: [
        'Tuesday 6-8 PM EST (peak engagement window)',
        'Thursday 6-8 PM EST (algorithm boost day)',
        'Sunday 10 AM - 12 PM EST (weekend browsing peak)'
      ],
      firstComment: `What ${niche} world should I create next? Drop your ideas! 🎨👇`,
      storyStrategy: `Post 3 behind-the-scenes stories within 1 hour: (1) The text prompt used, (2) A "before AI" comparison, (3) Poll: "Real or AI?" engagement driver`,
      engagementTips: [
        'Reply to every comment within the first hour — algorithm rewards early engagement',
        'Use the "Poll" sticker in Stories: "Real ocean vs AI ocean?"',
        'Pin the most insightful comment to drive thread discussions',
        'Engage with top accounts in the niche within 30 minutes of posting'
      ]
    },
    predictions: {
      expectedViews: '5,000-15,000 (new account) / 50,000-150,000 (established account)',
      expectedEngagement: '4-8%',
      viralPotential: 'Medium-High',
      reasoning: 'Novel concept (underwater AI city) + trending niche + question hook format + optimal posting time = strong viral signals'
    },
    challenges: [
      {
        challengedAgent: 'Content Strategist',
        issue: 'Hook text overlay "What if Atlantis ran on AI?" is a statement, not a question',
        fix: 'Questions drive 2x more comments than statements. Recommend changing to question format in caption to compensate.'
      },
      {
        challengedAgent: 'Trend Scout',
        issue: 'Recommend adding "AI disclosure" hashtags despite avoidList — community accounts actively search these',
        fix: 'Adding 3 AI disclosure tags to niche bucket to capture community traffic without over-disclosing in caption'
      }
    ],
    cost: { haiku: 0.008, total: 0.008 },
    duration: 5,
    mock: true
  };
}

module.exports = { getMockPostPackage };
